remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

title: Recipe Complexity and Ratings Analysis
description: An investigation into whether more complex recipes receive higher or lower ratings on Food.com
